### ISSUE TITLE
4.1.3 fix breaks createSelector() with more than one Parameter

### ISSUE THREAD

**Issue by JMS-1** [reduxjs/reselect#550]
You fixed https://github.com/reduxjs/reselect/issues/548 in 4.1.3 but now a createSelector() breaks with the same error message - it worked with 4.1.2 before.

```typescript
const some = createSelector(
    (a: number) => a,
    (_a: number, b: number) => b,
    (a, b) => a + b
)

export const test = some(1, 2)
```

![image](https://user-images.githubusercontent.com/3493757/142058437-10129d4b-b54c-46ce-9305-00fb93aaa6ab.png)

**Comment by markerikson** [comment]
*sigh*

I'll try to look at this tonight. Given this kind of simple scenario I don't understand why the typetests would have passed at all.

**Comment by arredgroup** [comment]
I have the same error, can you fix it???

**Comment by markerikson** [comment]
@arredgroup: comments that just say "I have the same problem" are _not_ helpful. What _is_ helpful would be providing examples that specifically show the error happening so that I can make sure I've fixed the issue.

**Comment by markerikson** [comment]
Also, and this may be very important: what versions of TypeScript are people using when they see this error?

**Comment by markerikson** [comment]
@JMS-1 : I can confirm that the code you provided works just fine with Reselect 4.1.3 and TS 4.4.4:

![image](https://user-images.githubusercontent.com/1128784/142080929-1cfc9942-3d44-4f8e-8ed3-6022b49446e8.png)

What version of TypeScript are you using?  As of Reselect 4.1, we require TS 4.1 or higher.

**Comment by markerikson** [comment]
Actually I'm doubly confused. Since Reselect's recent types rewrite only works in TS 4.2+, we provide a `typesVersions: <= 4.2` fallback to the old typedefs.

Can someone provide a sandbox or repo that reproduces this issue?

**Comment by markerikson** [comment]
At the moment I can't reproduce this. I'll leave this open, but I really need a repro to do anything about it.

**Comment by JMS-1** [comment]
This is the minimum repro I found (using typescript 4.4.4 and reselect 4.1.4). Just yarn and yarn build.

[repro.zip](https://github.com/reduxjs/reselect/files/7552628/repro.zip)

> **index.ts:9:29 - error TS2554: Expected 1 arguments, but got 2.**
> 
> yarn list v1.22.15
> ├─ reselect@4.1.4
> └─ typescript@4.4.4
> 

Switch to "reselect": "4.1.2" and there is no error, so it has to do with your 4.1.3 fix.

**Comment by JMS-1** [comment]
Bye the way: the same error is shown in the VSCode IDE. Did you reproduce with a real build or just look into the VSCode editor? This might make a difference since by default the editor uses its own version of typescript.

Regards

Jochen

**Comment by JMS-1** [comment]
Typescript Version 4.6[.0-dev.20211117] shows the same error, Typescript 4.3 will produce some other error.

**Comment by arredgroup** [comment]
I have Typescript 4.2.4, and I used @reduxjs/toolkit 1.5.1 that includes reselect "^4.0.0" and that is broken because now toolkit import reselect 4.1.3 and generate the same issue commented by JMS-1

**Comment by markerikson** [comment]
Huh. That is _extremely_ weird, because I added this exact same snippet to our typetest file while I was working on 4.1.4 yesterday, and it compiles fine.

I'm very confused what's going on here.

**Comment by markerikson** [comment]
This is bizarre. I copied the snippet into a new typetest file in the repo, and it showed the error. Then I restarted the TS server in VS Code, and it works okay.

This makes no sense at all :(

**Comment by quolpr** [comment]
I have the same issue. But if I wrap all selectors to the array like this:

```
const some = createSelector(
    [
        (a: number) => a,
        (_a: number, b: number) => b,
    ],
    (a, b) => a + b
)

export const test = some(1, 2)
```

Then the error gone

**Comment by quolpr** [comment]
Also funny fact 

https://codesandbox.io/s/twilight-breeze-jsusc?file=/src/index.ts

![image](https://user-images.githubusercontent.com/7958527/142248790-2a1728bf-caa7-4327-acab-0411b1ce119d.png)

If I miss typing for the second argument, selector stop working

**Comment by markerikson** [comment]
I just tried wrapping the inputs in an array in that repro project, and it didn't make a difference.

But, removing the `ExpandItems<>` line _did_ seem to let things build.

Maybe that's the issue here?

I'll have to investigate further this evening.

**Comment by eps1lon** [comment]
Fails with `strictNullChecks: false`: [Playground Link](https://www.typescriptlang.org/play?strict=false&noImplicitAny=false&strictNullChecks=false&strictFunctionTypes=false&strictPropertyInitialization=false&strictBindCallApply=false&noImplicitThis=false&noImplicitReturns=false&alwaysStrict=false#code/JYWwDg9gTgLgBAbwMZQKYEMaoMqoDapIzQC+cAZlBCHAORoDO+hMtAUG0hAHYPwPVUcALxwUGLLgJFoACjZxFcWegBccbgFcQAI1RQAlCIB8cdABoFS2QH01G7Xqjm4O9Vt36jw0zstLlC1dvU3Q4AGpXNgMOVAAPSFgxHj44LFTRARBUWQBGFwAmAyA)
Passes with `strictNullChecks: true`: [Playground Link](https://www.typescriptlang.org/play?strict=false&noImplicitAny=false&strictFunctionTypes=false&strictPropertyInitialization=false&strictBindCallApply=false&noImplicitThis=false&noImplicitReturns=false&alwaysStrict=false#code/JYWwDg9gTgLgBAbwMZQKYEMaoMqoDapIzQC+cAZlBCHAORoDO+hMtAUG0hAHYPwPVUcALxwUGLLgJFoACjZxFcWegBccbgFcQAI1RQAlCIB8cdABoFS2QH01G7Xqjm4O9Vt36jw0zstLlC1dvU3Q4AGpXNgMOVAAPSFgxHj44LFTRARBUWQBGFwAmAyA)

DefinitelyTyped packages are also only tested with `strictNullChecks` i.e. it's expected to run into issues if `strictNullChecks` are disabled.

**Comment by markerikson** [comment]
@eps1lon a-HA!  Thank you!

@JMS-1 @arredgroup    yeah, do you have `strictNullChecks` enabled?

**Comment by arredgroup** [comment]
@markerikson I don't use `strictNullChecks: true` because I have other libraries and code that are not compatible with that configuration

**Comment by markerikson** [comment]
@arredgroup in that case I'm going to need to see a more specific repro project from you to debug this further.

**Comment by markerikson** [comment]
Given that this appears to be a `strictNullChecks` problem, I'm going to close this issue.

If someone still has a repro that shows this happening when `strictNullChecks: true` is turned on, I can investigate further, but it appears that the code itself is working correctly.

**Comment by JMS-1** [comment]
> @eps1lon a-HA! Thank you!
> 
> @JMS-1 @arredgroup yeah, do you have `strictNullChecks` enabled?

Hm, at least not in my repro  from above - just using the default.

```json
{
    "compilerOptions": {
        "module": "commonjs",
        "moduleResolution": "node",
        "target": "es2019"
    },
    "include": [
        "index.ts"
    ]
}
```

**Comment by JMS-1** [comment]
Sadly enough I'm unable to migrate our code base to strictNullChecks: true at this moment so I stick on 4.1.2 for the moment.

Thanks for your investigation

Jochen

**Comment by doarrison** [comment]
Sorry to barge in on a closed issue but could we at least document somewhere that reselect requires strictNullChecks to be true? I say this as someone who woke up to all my builds breaking due to redux-toolkit automatically using the new version causing errors in a lot of selectors.

I realize its not feasible to handle every error caused by non-standard setups but it's still a bit unintuitive that a TS setting that handles null will somehow cause a problem with the number of parameters in a function. I also think that a certain amount of users will turn off typescript strict mode without realizing this defaults strictNullChecks to false.

**Comment by markerikson** [comment]
@doarrison Yeah, if someone wants to add a note on that to the README we can merge it.

That said, I honestly see `strictNullChecks: true` as a required baseline for any meaningful TS usage. We've seen multiple cases over in the RTK repo where people reported "type errors" of some kind, and it turned out that they had `strictNullChecks` turned off.  So, it's not like Reselect is the only library where turning that flag off is going to create problems in your own code.

Having that flag off both changes how TS is going to interpret library types, and opens up holes in your code.  Now, I'm not at all one of those people who goes around saying that "a single use of `any` will cause your codebase to burst into flames", and I [am perfectly fine with pragmatic use of TS types](https://blog.isquaredsoftware.com/2019/11/blogged-answers-learning-and-using-typescript/#pragmatism-is-vital).  `any` and `// @ts-ignore` are perfectly valid tools to use.

At the same time, switching that flag off _is_ weakening the typechecks that you do have, and leads to these kinds of problems.  I would much rather keep `strictNullChecks` on, and explicitly put a `// @ts-ignore` or a `type $FixTypeLater = any` to acknowledge that I'm having to work around the type system, then leave it off and have a change in behavior.

**Comment by JMS-1** [comment]
Works again with 4.1.5 without strictNullChecks. Thanks a lot!

**Comment by markerikson** [comment]
Heh, nice - I'll be honest and say that's completely accidental because I was just trying to get correct handling of `undefined` and optional parameters without even worrying about `strictNullChecks` at all, but glad it's working either way!

**Comment by Sincerite** [comment]
I still get this problem. I've tested on TypeScript 4.3.5, 4.5.2, few versions of Reselect and strictNullChecks true or false.

![image](https://user-images.githubusercontent.com/29306505/145243737-23cc1d25-c4c6-4358-bf79-26bbbf4317ab.png)
![image](https://user-images.githubusercontent.com/29306505/145243790-db970ced-ab28-483d-af26-1a89ceb0964f.png)
![image](https://user-images.githubusercontent.com/29306505/145243938-393a3e42-c3d4-4841-adfe-1aaeaac8ec1e.png)

Currently I'm back to Reselect 4.0.0 and it works.

What additional info do you need from me?

**Comment by markerikson** [comment]
@Sincerite ideally a project that reproduces the issue by itself.  

Just to check, does that second input selector for `getHandbookById` actually have its arguments typed?  The one that is `_, id) => id`.  If those aren't correctly typed, that's almost definitely going to break things.

**Comment by Sincerite** [comment]
Sorry but I can't understand what do you mean. This arrow function is meant for receiving id from end component and it always worked like that. I've never written any typings for that 'id' argument.
If this approach is wrong, please show me how you'd solve this problem. Thanks in advance.

**Comment by markerikson** [comment]
@Sincerite As of 4.1.x, Reselect _needs_ you to actually provide meaningful types for _all_ arguments in _all_ input selectors. Otherwise it can't figure out what the final argument types should be for the selector it's about to create.  Like, say, `(_: any, id: string) => id`.

**Comment by hduoc2003** [comment]
@markerikson, I have the same issues with **typescript ^5.2.2** and **@reduxjs/toolkit ^1.9.7** :((
![image](https://github.com/reduxjs/reselect/assets/59528331/23a47738-11bc-4ce7-b2c3-ff66da607019)
![image](https://github.com/reduxjs/reselect/assets/59528331/409f4a0e-3efd-41cc-9711-3d4e81b77c18)

**Comment by markerikson** [comment]
@hduoc2003 please file an entirely new issue, rather than commenting on one that was closed 2 years ago, and include a reproduction so that we can take a look.

**Comment by EskiMojo14** [comment]
(but for the record your third input selector should be `(state: RootState, semesterId: string, subjectId: string) => subjectId` - you're missing the second parameter)
