### ISSUE TITLE
TypeScript types appear to be broken in 4.1.5

### ISSUE THREAD

**Issue by mockdeep** [reduxjs/reselect#558]
When upgrading from 4.1.4 to 4.1.5, we started seeing a bunch of TypeScript complaints:

```
spec/javascript/responses/selectors_spec.ts:120:29 - error TS2322: Type '{ responses: { is_selected: boolean; }[]; are_all_selected_across_pages: boolean; meta: { pagination: { total_count: number; }; }; campaign_data: { doc_pages_count: number; }; }' is not assignable to type 'never'.

120     expect(canGeneratePdf({ responses })).toBe(true);
                                ~~~~~~~~~
```

```ts
const canGeneratePdf = createSelector([getSelectedResponsesCount], (selected_responses_count) => {
  const can_bulk_download_pdf = Feature.isActive('responses/bulk_download_pdf');

  return can_bulk_download_pdf || selected_responses_count <= default_page_size;
});
```

Not sure why the type `never` is being inferred from the arguments.

**Comment by markerikson** [comment]
Can you please show the entire source code for the selector and its inputs, and preferably as a CodeSandbox or repo that demonstrates this problem happening?  Also, do you have `strict: true` or `strictNullChecks: true` enabled in your TS config?

**Comment by mockdeep** [comment]
@markerikson hmm, I'll see what I can do. It's a pretty big private codebase. We don't have `strict` or `strictNullChecks` enabled at the moment.

**Comment by markerikson** [comment]
Okay, yeah, that's the first issue.  Per several other recent issue threads, **the current Reselect types expect that TS strict checks are turned on**, and will very likely produce incorrect results if that's turned off.

**Comment by mockdeep** [comment]
Oof, well we've got several thousand violations still in our codebase, so we're not going to be able to switch that on for a bit. I think we might need to keep reselect locked down to 4.1.4 for now.

**Comment by mockdeep** [comment]
Okay, I think I've got [a bare-bones repro](https://www.typescriptlang.org/play?strict=false&noImplicitAny=false&strictNullChecks=false&strictFunctionTypes=false&strictPropertyInitialization=false&strictBindCallApply=false&noImplicitThis=false&noImplicitReturns=false&alwaysStrict=false#code/JYWwDg9gTgLgBAbzgYygUwIYzQZTQGzWRmjgF84AzKCEOAcnQGcCiZ6BuAKC+QgDsm8AOZoYAQTgBeFOiy5WxaAAoA2sqHyAlNIB8cTdgB0AEwhom-GAFks2KAF0ANHGUB9YMP7Q01tDql9AFYtbj5BETEAIWlZTGw8QiUoNVEJZ1cPLx8-AP0YKABXf24uNKjlBDJQoA). It looks like the issue seems to have something to do with chained selectors.

**Comment by markerikson** [comment]
@mockdeep the first issue with that example is that none of the inputs are actually typed correctly. You _have_ to give their arguments meaningful types for `createSelector` to be able to infer anything.

**Comment by mockdeep** [comment]
@markerikson that's the dream, but when we're trying to introduce TypeScript to an existing codebase it's an ongoing process. I'll add types to those and see what happens.

**Comment by mockdeep** [comment]
Okay, adding some more types to the selectors got it to pass type checking. I can understand it might be pretty difficult for you to sort out typing on your end, but it's also not quite ideal that a patch release would cause our build to break.

**Comment by markerikson** [comment]
That is unfortunately the nature of TS in general :(  You can see in the recent release history how we've been iterating and fixing things up after the Reselect 4.1 release.  

When I published 4.1, it passed all the existing type tests, and it had a fallback to the old types for anyone using TS 4.1 and earlier.  So, I assumed everything was good to go.

Since then, people have reported various breaking issues: the parameters types were getting unioned instead of intersected, the intersecting wasn't working right, etc, etc.  

We're doing our best to make the types as correct as possible. Trust me, I don't _want_ to have anyone's builds breaking :)  but we also can't predict exactly how everyone is going to use the library, and as you've seen, what gets fed in to the API can greatly change how the types behave.  So, there's a big distinction between "good-faith attempt to improve things that causes someone's build to break due to unforeseen complications", and "intentional major change to how the API is designed that _will_ cause existing code to break".  All of the Reselect 4.1.x releases have been published with the intent of keeping existing code working as-is, or at most needing minor code changes that remove incorrect usages, rather than a deliberate breaking change to the API.

**Comment by ahce** [comment]
@markerikson generic types are broken too
<img width="511" alt="imagen" src="https://user-images.githubusercontent.com/12452003/147272711-190e245d-f383-469d-a177-26f0146814ad.png">

```
import { createSelector } from 'reselect';

const getValue = <T>(value: T): T => value;

const makeGetValue = () =>
  createSelector(
    ({ data: { value } }: { data: { value: string } }) => value,
    // (v) => v,
    getValue,
  );

const value: string = makeGetValue()({ data: { value: 'value' } });

export default value;

```

**Comment by markerikson** [comment]
@ahce : is this a real example, or one that's just trying to illustrate generic usage? Because that selector as written is not the right way to use Reselect conceptually. You should never write an "output selector" that is just `x => x` - there's no actual memoization happening.  

Additionally, you should never continually call `createSelector()` every time like that, because it always generates a new selector instance and _that_ can never memoize properly.

In general, the way the 4.1.x types work is you _must_ provide actual types for all of the "input selectors", and Reselect will infer the resulting generated selector parameters and the types of the arguments for the "output selector".  You shouldn't have to provide any types for that output selector yourself.

**Comment by ahce** [comment]
@markerikson is an example with generic types

**Comment by markerikson** [comment]
Yeah, like I said, that's not how you're supposed to use Reselect at all in the first place, TS or otherwise :(

If you can put together a different example that actually matches how Reselect is supposed to be used and demonstrates a problem, I'd definitely be interested.

**Comment by codeaid** [comment]
Updated to 4.1.5 and also have types broken that worked fine before.

Some parts of my code:

```typescript
// types.ts
export type Animal = { ... }
export type Elephant = Animal & { ... }
```

```typescript
// reducers.ts
import { createReducer } from 'typesafe-actions';

const entitiesReducer = createReducer<Record<string, Elephant>>({});
const idsReducer = createReducer<Array<string>>([]);
const selectedReducer = createReducer<Array<string>>([]);
```

```typescript
// selectors.ts
const getElephantState = (state: State) => state.elephants;

const getElephantEntities = createSelector(
  getElephantState,
  state => state.entities,
);

const getElephantIds = createSelector(
  getElephantState,
  state => state.ids
);

const getElephantSelection = createSelector(
  getElephantState,
  state => state.selected,
);

const getElephants = createSelector(
  getElephantEntities,
  getElephantIds,
  (animals, ids) => filterMapByKeys(animals, ids).filter(isNotEmpty),
);

export const getSelectedElephantList = createSelector(
  getElephants,
  getElephantSelection,
  filterAnimalsByIds,
);

```

```typescript
// utils.ts
const filterListByKeys = <TEntity>(
  entities: Array<TEntity>,
  keys: Array<string>,
  getKey: (entity: TEntity) => string,
) => {
  const set = new Set(keys);
  return entities.filter(entity => set.has(getKey(entity)));
};

export const filterMapByKeys = <TEntity>(
  entities: Record<string, TEntity>,
  keys: Array<string>
) => keys.map(key => entities[key]).filter(isNotEmpty);

export const filterAnimalsByIds = <TAnimal extends Animal>(
  animals: Array<TAnimal>,
  ids: Array<string>,
) => filterListByKeys(animals, ids, getAnimalId);

export const isNotEmpty = <TValue>(value: TValue | null | undefined): value is TValue =>
  typeof value !== 'undefined' && value !== null;
```

```typescript
// component

const selectedElephantList = useSelector(getSelectedElephantList);
```

Previously `selectedElephantList` would result in `Elephant[]`, now it results in `Animal[]`. 4.1.2
seems to work whereas 4.1.3 breaks, so it must be something in that release.

Now that I've reverted back to 4.1.2 a different typing issue occurs:

```typescript
// types.ts
export type SortDirection = 'asc' | 'desc';

export interface SelectorSortDirectionProps {
  sortDir?: SortDirection;
}

export interface SelectorSortFieldProps {
  sortKey?: string;
}
```

```typescript
// utils.ts
export const getSelectorSortDirection = (state: State, props: SelectorSortDirectionProps) =>
  props.sortDir;

export const getSelectorSortKey = (state: State, props: SelectorSortFieldProps) => 
  props.sortKey;
```

```typescript
// selectors.ts
export const getZebraEntityList = createSelector(
  getZebraEntityMap,
  getZebraIds,
  getSelectorSortDirection,
  getSelectorSortKey,
  (entityMap, ids, sortDir, sortKey) =>
    getSortedEntityList(filterMapByKeys(entityMap, ids), sortKey, sortDir, ['name']),
);
```

This is causing the following error, which I didn't have before:

![image](https://user-images.githubusercontent.com/637799/148976551-fa2e10a4-7d7d-48f8-b00f-1f7c911565bc.png)

Reverting back to 4.0.0 fixes it but even going up one release to 4.1.0-alpha.0 it breaks.

**Comment by markerikson** [comment]
@codeaid : could you put together a repo or CodeSandbox that shows this behavior?

**Comment by MingyaoLiu** [comment]
I have the same issue similar usage as @codeaid .
Revert back to 4.0 works.

**Comment by markerikson** [comment]
@MingyaoLiu : I'll ask the same thing: **please provide a CodeSandbox or repo that demonstrates the problem**.

Just saying "I have the same problem" does _not_ give me any information I can use to try to fix things.

**Comment by MingyaoLiu** [comment]
> @MingyaoLiu : I'll ask the same thing: **please provide a CodeSandbox or repo that demonstrates the problem**.
> 
> Just saying "I have the same problem" does _not_ give me any information I can use to try to fix things.

Hi sorry I can't help with that in the moment, as I'm not very knowledgable on reselect. I'm working on doing a full upgrade on our build process, and I run into issues around this. I did downgrade all reselect in our packages to 4.0.0, and the build process is fixed.

**Comment by markerikson** [comment]
@MingyaoLiu fwiw I'm not asking you to fix the actual problem :)

I'm asking you to:

- Look at _your_ app code that is showing an error
- Try to create a very small standalone project that uses the same code patterns and also has the same error

FWIW, it's very possible that there _may_ actually be a problem with the _app_ code.  Reselect 4.1.x does a much better job of handling the TS types of all of the input selectors than 4.0 did.

But it _could_ also be a bug in Reselect.  And I can't know whether it's _our_ problem or _your_ problem if you can't provide me any actual info.  For that matter, so far you haven't even said what actual error message you're seeing :)

The only way I can investigate is to see what some actual code that produces the error, and the best way to do that is to create a minimal standalone example project (preferably using CodeSandbox) so that I can try it out myself.

**Comment by MingyaoLiu** [comment]
yah that's true, if I have time I will try to create something.

**Comment by codeaid** [comment]
@markerikson Hey, sorry for the late reply. Here's a repo reproducing both of the issues:
https://codesandbox.io/s/reselect-issue-558-o3n52?file=/src/index.tsx

The way to test it is:
1. Ensure `reselect` is at v4.0.0 in the left dependencies panel and notice how the `results` variable in `index.tsx` is `Elephant[]` if you Ctrl/Cmd hover over it.
2. Also notice how there are no errors in the `getSortedElephantEntityList` call on line 25.
3. Change the version of Reselect to 4.1.5 in the left panel
4. Notice how `results` is now `Animal[]` and the call on line 25 errors out not understanding the merge of two parameter selectors `getSelectorSortDirection` and `getSelectorSortKey` in the `selectors.ts` file.

Hope this helps and thanks for looking into it!

**Comment by MingyaoLiu** [comment]
any update?

**Comment by MingyaoLiu** [comment]
Thanks just checking in trying to learn more about this issue.

**Comment by markerikson** [comment]
@codeaid : I'm finally taking a look at this, and tbh I have two thoughts:

- The example still feels overly complicated and would be easier to follow if you could shrink this down further
- That said, looking at the very last step, I'm not convinced this is a "bug" per se.

If we skip the rest of the app and logic, what it seems to boil down to is:

```ts
  const getElephants = createSelector(
    getElephantEntities,
    getElephantIds,
    (animals, ids) => filterMapByKeys(animals, ids).filter(isNotEmpty)
  )

  const getElephantSelection = createSelector(
    getElephantState,
    state => state.selected
  )

  const filterAnimalsByIds = <TAnimal extends Animal>(
    animals: Array<TAnimal>,
    ids: Array<string>
  ) => filterListByKeys(animals, ids, getAnimalId)

  const getSelectedElephantList = createSelector(
    getElephants,
    getElephantSelection,
    filterAnimalsByIds
  )

  const results = getSelectedElephantList(store.getState())
```

and while both `getElephants` and `getElephantSelection` are typed as dealing with `Elephant` values, **`filterAnimalsByIds` is already typed as dealing with `Animal` values, so that's what the final return type is**.

At this point, I've seen a couple different "reproductions" added to this thread, but neither of them _appear_ to be real actual bugs.  The first sandbox at https://github.com/reduxjs/reselect/issues/558#issuecomment-982209763 was invalid use of Reselect overall, and the one at https://github.com/reduxjs/reselect/issues/558#issuecomment-1020426657 seems like the code is working correctly based on the provided types.  Additionally, the very first examples provided appeared to be broken due to lack of strict null checks.

Given that, I'm going to close this.

If someone can put together a better reproduction that shows real problems happening with Reselect 4.1.5+, please file a new issue.

**Comment by jacobroufa** [comment]
I ran into this issue recently when trying to consume a library that used reselect and was targeting `^4.0.0`, after updating the application to target the latest version `^4.1.7`. Once I updated the library the issue went away.

@markerikson do you have any advice in the case that I would not be able to update the library? Stick to targeting the old version?

**Comment by markerikson** [comment]
@jacobroufa what "issue" are you seeing, specifically?

**Comment by jacobroufa** [comment]
Apologies @markerikson. I was seeing that my input type `is not assignable to type 'never'` when I expected it to point to the interface of my state object.

After not seeing the error when creating the exact same selector in my own application codebase (targeting reselect `^4.1.7`), I consumed the library (internal to my company) which targeted the older version of reselect (`^4.0.0`) and the error came up. I do not know how to provide this as a reproduction within a codesandbox -- can that emulate consuming a second sandbox as a library?

The selector I was using is very simple, e.g.:
```ts
import { selectIsLoading as librarySelectIsLoading } from 'myLocalLibrary'; // library targets 4.0.0 reselect
import { createSelector } from 'reselect'; // 4.1.7 reselect

interface IState {
  isLoading: boolean;
}

const selectState = (state: IState): IState => state || {} as IState;

const selectIsLoading = createSelector(
  selectState,
  (state: IState): boolean => state.isLoading || false
);

const state: IState = { isLoading: true };

// if using local selector as above, no error
selectIsLoading(state);

// error TS2345: Argument of type 'IState' is not assignable to parameter of type 'never'.
librarySelectIsLoading(state);
```

**Comment by markerikson** [comment]
My immediate assumption would be that trying to mix and match selectors created with 4.1.x and 4.0 would be incompatible, because of the completely different TS type definitions.  I would strongly recommend trying to get this internal library updated to use 4.1.x, which has much better TS inference overall.

**Comment by jacobroufa** [comment]
Sounds good. I intend to update this library; it's internal so thankfully I have a bit of say here. I am more asking for the benefit of others who may not have that capability, if you can point to a specific incompatibility between type definitions. No worries if not!

By "targets 4.0" I mean that the library I am consuming has 4.0 as a dependency. If I `git grep reselect` I see several references including that 4.0 dependency in my package-lock.json, and even though as you can see it resolves in both cases (locally and within the consumed module) to 4.1.7, I still get the aforementioned type error when I run `tsc` on my application:
```
package-lock.json:        "reselect": "^4.1.7"
package-lock.json:        "reselect": "^4.0.0",
package-lock.json:    "node_modules/reselect": {
package-lock.json:      "resolved": "https://registry.npmjs.org/reselect/-/reselect-4.1.7.tgz",
package-lock.json:        "reselect": "^4.0.0",
package-lock.json:    "reselect": {
package-lock.json:      "resolved": "https://registry.npmjs.org/reselect/-/reselect-4.1.7.tgz",
```

**Comment by markerikson** [comment]
Yeah, I'd really need to see a repo or sandbox that demonstrates an issue happening at this point so I can poke at it myself.
