### ISSUE TITLE
Create selector type inference works in 4.1.2 and breaks in 4.1.4

### ISSUE THREAD

**Issue by kompot** [reduxjs/reselect#555]
Sort of relates to #554 but decided to create a separate issue as this has reproducible repo.

Please checkout this repo
https://github.com/kompot/reselect-4.1.2-4.1.4-bug
and run `yarn run typecheck`. 

No issues found, type inference works as expected in 4.1.2.

After upgrading to 4.1.4 (`yarn add reselect@4.1.4`) the following errors arise.

```
src/reselect-bug.ts:24:46 - error TS2554: Expected 1 arguments, but got 2.

24 const selectorResult1 = someSelector1(state, undefined);
                                                ~~~~~~~~~

src/reselect-bug.ts:25:46 - error TS2345: Argument of type 'undefined' is not assignable to parameter of type '{}'.

25 const selectorResult2 = someSelector2(state, undefined);
                                                ~~~~~~~~~
```

So there are problems with optional params in this code
https://github.com/kompot/reselect-4.1.2-4.1.4-bug/blob/657dfefdc1a5381dcc180172375e54f954d43568/src/reselect-bug.ts#L10-L20

We've got dozens of such cases with optional params of different nature and 4.1.4 broke hundrends of our selectors. 

4.1.2 worked great, we have actually found lots of bugs by just upgrading to 4.1.2. Thanks!

**Comment by markerikson** [comment]
This _should_ now be fixed in https://github.com/reduxjs/reselect/releases/tag/v4.1.5 .  Please let us know if there's any further issues!

**Comment by renjithspace** [comment]
Hi @markerikson 

It seems this is not fixed. Still can't pass the second argument to a selector. It throws `Expected 1 argument, but got 2` from typescript.

Here's my code:

```ts
/*
  * toolkit version is 1.7.1
  * and it using reselect version 4.1.5
  */
import { createSelector } from '@reduxjs/toolkit'

const isActiveTopic = createSelector(
  [state => state.topics.activeId, (state, checkId) => checkId], // Second argument is here
  (activeId, checkId) => checkId === activeId
)

const makeMapState = (state: RootState) => {
  return {
    isActive: isActiveTopic(state.topics.activeId, 28) // Expected 1 arguments, but got 2.
  }
}
```

**Comment by renjithspace** [comment]
Hi @markerikson,

Ignore it. It worked fine after I explicitly annotated the types. 🔥
```ts
const isActiveTopic = createSelector(
  [
    (state: RootState) => state.topics.activeId,
    (state: RootState, checkId: number) => checkId
  ],
  (activeId: number, checkId: number) => checkId === activeId
)
```

**Comment by markerikson** [comment]
Yep, that's exactly the point :) You _must_ type the input selectors correctly.
